# 워크 플로의 이름
name: CI

# 워크 플로의 시작 조건: main 브랜치에 push
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경
    # 작업의 실행 단계를 정의
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant exceute permission for gradlew
        run: chomd +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
